serviceAccount:
  controller:
    create: true
    name: ebs-csi-controller-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::243746944939:role/AmazonEKS_EBS_CSI_DriverRole

node:
  tolerateAllTaints: true