apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
images:
  - name: 243746944939.dkr.ecr.us-east-1.amazonaws.com/payment-platform
    newTag: 034e9bf2504c9bce5f65f01ff1276b0eb11d5f76
