apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
images:
  - name: 243746944939.dkr.ecr.us-east-1.amazonaws.com/payment-platform
    newTag: 6242b233ab9aff6822b2d86f806993110a526885
