apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
images:
  - name: 243746944939.dkr.ecr.us-east-1.amazonaws.com/payment-platform
    newTag: bcb9973a14433697c036c33e7a21368e224c623d
